# Generated by Django 2.0.6 on 2018-06-26 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artistas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_artista', models.CharField(help_text='Nombre del artista', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataArtista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.TextField(blank=True, help_text='Título del disco', max_length=500)),
                ('bio', models.TextField(blank=True, help_text='Link al video', max_length=1000)),
                ('foto_artista', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Artistas')),
            ],
        ),
        migrations.CreateModel(
            name='Discos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Título del disco', max_length=50, null=True)),
                ('brief', models.TextField(blank=True, help_text='Propietario de los links', max_length=300, null=True)),
                ('creditos', models.TextField(blank=True, help_text='Créditos del disco', max_length=500, null=True)),
                ('fecha', models.IntegerField(blank=True, help_text='Año de publicación', null=True)),
                ('foto_disco', models.ImageField(blank=True, help_text='Arte de tapa', null=True, upload_to='')),
                ('link_spotify', models.CharField(blank=True, help_text='Link para escuchar en la web', max_length=300, null=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Artistas')),
            ],
        ),
        migrations.CreateModel(
            name='EstatusProyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus_proyectos', models.CharField(help_text='Estatus de proyecto', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fechas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, help_text='Fecha del concierto')),
                ('hora', models.TimeField(blank=True, help_text='Hora del concierto')),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad', max_length=50)),
                ('venue_name', models.CharField(blank=True, help_text='Venue', max_length=50)),
                ('venue_direc', models.CharField(blank=True, help_text='Dirección', max_length=50)),
                ('venue_link', models.URLField(blank=True, max_length=128, verbose_name='Web')),
                ('ticket_link', models.URLField(blank=True, max_length=128, verbose_name='Link a venta de entradas')),
                ('ticket_price', models.IntegerField(blank=True, help_text='Precio de las entradas')),
                ('venue_google_maps', models.CharField(blank=True, help_text='Link de Google maps', max_length=50)),
                ('cache_total', models.IntegerField(blank=True, help_text='Precio de las entradas')),
                ('fee_booking', models.IntegerField(blank=True, help_text='Fee porcentual')),
                ('gastos', models.IntegerField(blank=True, help_text='Fee porcentual')),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios', max_length=500)),
                ('forma_de_pago', models.TextField(blank=True, help_text='Forma de pago', max_length=500)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Artistas')),
                ('estatus_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.EstatusProyectos')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, max_length=128, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, max_length=128, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, max_length=128, verbose_name='Youtube')),
                ('twitter', models.URLField(blank=True, max_length=128, verbose_name='Twitter')),
                ('spotify', models.URLField(blank=True, max_length=128, verbose_name='Spotify')),
                ('itunes', models.URLField(blank=True, max_length=128, verbose_name='Itunes')),
                ('web', models.URLField(blank=True, max_length=128, verbose_name='Web')),
                ('apple', models.URLField(blank=True, max_length=128, verbose_name='Apple')),
                ('amazon', models.URLField(blank=True, max_length=128, verbose_name='Amazon')),
                ('deezer', models.URLField(blank=True, max_length=128, verbose_name='Aeezer')),
                ('google', models.URLField(blank=True, max_length=128, verbose_name='Google')),
                ('pandora', models.URLField(blank=True, max_length=128, verbose_name='Pandora')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Artistas')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Título del disco', max_length=50)),
                ('link', models.CharField(blank=True, help_text='Link al video', max_length=300)),
                ('destacado', models.BooleanField(help_text='Destacar el video?')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Artistas')),
            ],
        ),
    ]
